### ISSUE TITLE
Things for newbies to do

### ISSUE THREAD

**Issue by ManUtdNZ** [gpaulissen/bml#3]
Hi
Could you add "Things to do" that newbies like myself should do at the start before even thinking of posting a query/bothering you with "how to" messages?

For example, 
1. I use Notepad++, it became essential I changed TAB to spaces to meet the need of an even number of spaces on indentation otherwise conversions to always work.
2. Colour coding spaces/TAB characters would help to ensure the spacing requirements are met.

Links on how to do these minors configurations to Notepad++ would be beneficial.

Not a grumble. Trying to save you time.

**Comment by gpaulissen** [comment]
1. I use Emacs with whitespace-mode to get all the nice colours but in my opinion Emacs is for old style Unix programmers like me. Notepad++ is easier for most humans :) I do not know how to get the colours in Notepad++ anyhow (since I do not use it for BML).
2. I will make a remark about the TAB characters in the README.

**Comment by gpaulissen** [comment]
Editor paragraph will be added to README version 2.2.0
